<!DOCTYPE html>
<html>
<head>
<title>The Juvenile Justice (Care and Protection) of Children Act of 2000</title>
</head>
<body bgcolor="#F3CEC1">
<a href="lofaal.php">Acts and Lows > </a>The Juvenile Justice (Care and Protection) of Children Act of 2000
<h3>The Juvenile Justice (Care and Protection) of Children Act of 2000:</h3>
<p>The Government of India enacted the Juvenile Justice Act in 1986. In 1989 the General Assembly of the United Nations adopted the Convention on the Rights of a Child. India ratified the UNCRC in 1992. The convention outlines the right of the child to reintegration into society without judicial proceedings where avoidable. Hence the Government, to fulfil the standards of the convention felt a need to re-write the law. Hence in 2000 the old law was replaced by the Juvenile Justice (Care and Protection of Children) Act. 
</p>
<p>
In this act a child or juvenile is defined as a person who has not completed his/her 18th year of age. It outlines two target groups: Children in need of care and protection and Juveniles in conflict with law. This act protects not only the rights of children, but a person's rights when he/she was a child. Meaning that if a crime or an incident took place while the person was a child, and then during the proceeding the juvenile ceased to be of age the case would continue as if the juvenile has not turned eighteen yet. 
</p>
<p>
The second chapter of the Act addresses Juveniles in Conflict with Law (JCLs). This section calls for the establishment of Juvenile Justice Boards (JJBs) where the State Government sees fit. JJBs must contain a Metropolitan or Judicial magistrate and two social workers where one of the workers must be a woman. The magistrate is required to have a background in child psychology or child welfare. JCL cases can only be heard in the JJB and not by another court. The powers of the JJB can be exercised in a High court or Court of Session when an appeal has been made as part of the act, the state is required to set up a number of institutions where the needs and protection of juveniles may be fulfilled. For the reception and rehabilitation of JCLs the state must set up Observation Homes and Special Homes in ever district or group of districts. The state may directly set up these homes or contract a voluntary organisation to do so. Observation homes are for institutions for juveniles while their proceedings are underway. After the proceedings of a particular case are complete, the JJB may decide that the rehabilitation of the child is not complete and hence place them in a Special home for no longer than three years.  
</p>
<p>
When a police officer comes in contact with a juvenile he must place the child with the Special Juvenile Police Unit (SJPU) who must report the child to the board without delay. Bail is available to juveniles in all cases as long as the Board find the release of this child will not place him in any danger or in the influence of criminals. If the child is not released on bail he is only to be placed into the custody of an Observation Home. The SJPU are responsible for informing the juvenile's parents of the arrest, as well as inform the Probation Officer who will make the necessary enquires about the child. 
</p>
<p>
The JJB must make an inquiry into the case and if they determine the child is guilty of the crime then they may release the child after advice and counselling. The child can be released either to his parents/guardians or into an institution, with or without a bond. The Board may also make the child pay a fine (if he is above fourteen and earns) or complete hours of community service. A social investigation report from the probation officer is required for the child to be discharged. The probation officers may be required to continue a follow up of the child even after discharge. A child can not be charged with the death penalty, imprisonment which can extend to life imprisonment or committed to prison for inability to pay a fine or providing a security for the bond. 
</p>
<p>
Under this act juvenile cases can not be processed with non-juvenile cases. A juvenile can not be rendered unfit or 'disqualified". Juveniles are not exposed to the media as magazines, news papers and visual media are not permitted to release the information about the juvenile. Juveniles who run away from the Observation or Special homes can be brought back without a warrant and without punishment. Cruelty (such as assault or neglect) towards juveniles in the home or by any person in charge of him/her is a punishable offence. This act also has provisions to penalize people who exploit children for a crime. A person, who employs a child in a hazardous industry, employs him/her for begging or provides a child with drugs or alcohol is liable to serve prison time and pay fines.
</p>
<p> 
Chapter III address Children in Need of Care and Protection (CNCP). In place of a JJB, CNCP cases are heard by the Child Welfare Committee (CWC). The committee is meant to have a chairperson and four other members of whom at least one should be a woman and at least one expert in children's issues. The purpose of the CWC is to provide for the care, treatment, protection, rehabilitation and development of the child and in doing so uphold the rights of the child. The child may be brought in front of the CWC by a police office, public servant, social worker, CHILDLINE, the child or anyone public citizen. The committee may commit a child to the Children's home or a Shelter home if the child has no immediately available family or support system. 
Like in the case of JCL, CNCP are provided with Children's Homes and Shelter Homes. The state may directly set up these homes or contract a voluntary organisation to do so. Shelter homes are for children whose family can not be located or whose case has been completed. Children who come from a different area or state are meant to be transferred to an institution and CWC that is closest to his/her residence. The main aim of this system is to restore the child to his family or family environment after determining the safety of the environment. 
</p>
<p>
The fourth chapter discusses the importance of rehabilitation and social integration as the purpose of this act. This section discusses certain non-institutional solutions such as adoption, foster care, and sponsorship. Orphaned and abandoned children are eligible for adoption. The CWC may declare a child fit for adoption and refer him/her to an adoption agency (set up by the government) for placement. Foster care in this act is only for looking after infants before adoption takes place. Sponsorship programmes are to help provide supplementary educational, nutritional, medical and other services to families, guardians, and homes. After-care organisations are also to be set up to take care of children after they leave the homes.  
</p>
<p>
The last chapter of the act contains many miscellaneous provisions. Some of the notable provisions are as follows. The act allows for children with special needs such as a mental or physical disease to be given the necessary attention at an approved institution that specialises in the form of care. Under this act the government can set up advisory boards at different levels to advise them about various implementation aspects of the act. The JJB and CWC have the authority to release a child to his/her parents or give the child leave because of a death in the family, a wedding, a school examination, etc. For the carrying out of this act, the state shall create a Child Protection Unit, whose officers are responsible to ensure that the act is properly implemented. Rules for this act are to be made by each State Government. 
To access CHILDLINE publications regarding the JJ Act click on the following links: Child Protection & JJ System for Children in Need of Care & Protection and Child Protection & JJ System forJuveniles in Conflict with Law
</p>
</body>
</html>